"""outras alterações

Revision ID: 038284490af9
Revises: 83ea42cb9a8a
Create Date: 2025-10-08 20:47:17.511862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038284490af9'
down_revision: Union[str, Sequence[str], None] = '83ea42cb9a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('statusVotacao', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'statusVotacao')
    # ### end Alembic commands ###
