"""initial_migration

Revision ID: 23b9da4b6685
Revises: 
Create Date: 2025-11-13 14:53:18.042674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b9da4b6685'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('eleicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('statusVotacao', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('eleicao_candidato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_election', sa.Integer(), nullable=False),
    sa.Column('fk_candidate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_candidate'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['fk_election'], ['eleicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_eleicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_election', sa.Integer(), nullable=False),
    sa.Column('encrypted_tally', sa.String(), nullable=False),
    sa.Column('total_candidates', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fk_election'], ['eleicoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_election')
    )
    op.create_table('votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.Column('fk_election_candidate', sa.Integer(), nullable=False),
    sa.Column('encrypted_vote', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fk_election_candidate'], ['eleicao_candidato.id'], ),
    sa.ForeignKeyConstraint(['fk_user'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    op.drop_table('registro_eleicao')
    op.drop_table('eleicao_candidato')
    op.drop_table('usuarios')
    op.drop_table('eleicoes')
    op.drop_table('candidatos')
    # ### end Alembic commands ###
