"""14-11-2025-16:13

Revision ID: 51ff67aac2d9
Revises: 23b9da4b6685
Create Date: 2025-11-14 19:13:38.192802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ff67aac2d9'
down_revision: Union[str, Sequence[str], None] = '23b9da4b6685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votos', sa.Column('zk_proof', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votos', 'zk_proof')
    # ### end Alembic commands ###
