"""11-11-2025-20:29

Revision ID: 906ae8318e7a
Revises: 6bb17667af7c
Create Date: 2025-11-11 23:29:41.312837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906ae8318e7a'
down_revision: Union[str, Sequence[str], None] = '6bb17667af7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('eleições',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eleicao_candidato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_election', sa.Integer(), nullable=False),
    sa.Column('fk_candidate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_candidate'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['fk_election'], ['eleições.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.Column('fk_election_candidate', sa.Integer(), nullable=False),
    sa.Column('total_votes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['fk_election_candidate'], ['eleicao_candidato.id'], ),
    sa.ForeignKeyConstraint(['fk_user'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    op.drop_table('eleicao_candidato')
    op.drop_table('eleições')
    op.drop_table('candidatos')
    # ### end Alembic commands ###
